### ISSUE TITLE
Is angular-google-charts compatible with angular 6.0.0?

### ISSUE THREAD

**Issue by markkoehn** [FERNman/angular-google-charts#32]
When I compile my Angular application with @angular/core 6.0.0  and angular-google-charts - the typescript compiler complains:
ERROR in node_modules/angular-google-charts/lib/google-charts.module.d.ts(5,44): error TS2315: Type 'ModuleWithProviders' is not generic
We are currently tied to version 6.0.0 of angular because of other dependencies.  I was wondering it here is a way to get this component to work with version 6.0.0 of angular as well.
Thank you,
Mark

**Comment by mosh-ackosoft** [comment]
angular-google-charts@0.1.3 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0 but none is installed.

**Comment by FERNman** [comment]
@mosh-ackosoft What do you mean? You have to install Angular to use this framework.
