### ISSUE TITLE
Namespace 'google.visualization' has no exported member 'ChartEditor'

### ISSUE THREAD

**Issue by FrankL-git** [FERNman/angular-google-charts#167]
# Bug Report

## Description
After having installed 1.1.5 (npm install angular-google-charts@latest), the ng serve command gives the errors below. Inspite of the errors, the charts are displayed correctly.
After removing 1.1.5 and installing 1.1.4 everything runs fine.

## To reproduce
see above.

## Exception or Error
<pre><code>
ERROR in node_modules/angular-google-charts/lib/components/chart-editor/chart-editor-ref.d.ts:7:46 - error TS2694: 
Namespace 'google.visualization' has no exported member 'ChartEditor'.

7     constructor(editor: google.visualization.ChartEditor);

node_modules/angular-google-charts/lib/components/chart-editor/chart-editor.component.d.ts:14:72 - error TS2694: 
Namespace 'google.visualization' has no exported member 'ChartEditor'.

14     get initialized$(): import("rxjs").Observable<google.visualization.ChartEditor>;

node_modules/angular-google-charts/lib/components/chart-editor/chart-editor.component.d.ts:24:67 - error TS2694: 
Namespace 'google.visualization' has no exported member 'ChartEditorOptions'.

24     editChart(component: ChartBase, options: google.visualization.ChartEditorOptions): ChartEditorRef;

node_modules/angular-google-charts/index.d.ts:1:23 - error TS2688: 
Cannot find type definition file for 'libs/angular-google-charts/src/types/google.visualization'.

1 /// <reference types="libs/angular-google-charts/src/types/google.visualization" />

</code></pre>

## Your environment
<pre><code>

Angular CLI: 10.1.0
Node: 12.18.3
OS: linux x64

Angular: 10.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1001.0
@angular-devkit/build-angular     0.1001.0
@angular-devkit/build-optimizer   0.1001.0
@angular-devkit/build-webpack     0.1001.0
@angular-devkit/core              10.1.0
@angular-devkit/schematics        10.1.0
@angular/cdk                      10.2.0
@angular/material                 10.2.0
@ngtools/webpack                  10.1.0
@schematics/angular               10.1.0
@schematics/update                0.1001.0
rxjs                              6.6.3
typescript                        3.9.7
webpack                           4.44.1

</code></pre>

**Comment by FERNman** [comment]
What version of `@types/google.visualization` do you have installed?

**Comment by FrankL-git** [comment]
The version is @types/google.visualization@0.0.52.
In the node_modules/angular-google-charts/lib/components/chart-editor/chart-editor-ref.d.ts there is the /// reference path section:
<pre>
/// <reference types="@types/google.visualization" />
</pre>

**Comment by FrankL-git** [comment]
Sorry, I pressed the "close" button unintentionally

**Comment by onkar82kubal** [comment]
Hi All,

I am facing same issue. I was using 1.1.4 initially then i upgraded to 1.1.5. But no changes.
Please provide the fix.  This has stooped my deployment process.

**Comment by FERNman** [comment]
@FrankL-git I think it's because the Typescript dependency was updated by updating this library to Typescript v4. If anybody knows the fix, I'd be happy to hear it!

**Comment by FrankL-git** [comment]
@FERNman With the following hack (which may give you an idea for the error's cause (I'm not a typescript expert at all)) the errors disappeared. 
Step1: In node_modules/angular-google-charts/index.d.ts I changed
<pre>
/// &lt; reference types="libs/angular-google-charts/src/types/google.visualization"/>
</pre>
(which references a not existing file) to (simply taking the path which is in the 1.1.4 version of the file):
<pre>
/// &lt; reference path="types/google.visualization/index.d.ts" />
</pre>
Step2: I created the (in 1.1.4. existing) directory
<pre>
 node_modules/angular-google-charts/types/google.visualization
</pre>
Step3: I copied (from 1.1.4) the file 
<pre>
node_modules/angular-google-charts/types/google.visualization/index.d.ts
</pre>
into the just created directory.

**Comment by pcaridade-icg** [comment]
After upgrading my project from Angular 9.1.12 to 10.0.14 ("typescript": "~3.9.7"), I'm facing the same problem with both versions 1.1.4 and 1.1.5 .
Now, I'm unable to build the project for production (--prod).

**Comment by FERNman** [comment]
@FrankL-git thanks for the detailed comment. The problem is that Typescript (or maybe Webpack) doesn't include the types in the output anymore.

@pcaridade-icg I'm pretty sure you should be able to use 1.1.4, even when using Angular 10.

**Comment by FrankL-git** [comment]
@FERNman Don't you think that the main problem is the line
<pre>
/// &lt; reference types="libs/angular-google-charts/src/types/google.visualization"/>
</pre>
in the node_modules/angular-google-charts/index.d.ts file? As far as I understand &lt; /// reference types="something" &gt; the something must be a directory containing an index.d.ts file. And the errormessage mentioned in my first comment says: 
<pre>
node_modules/angular-google-charts/index.d.ts:1:23 - error TS2688: 
Cannot find type definition file for 'libs/angular-google-charts/src/types/google.visualization'.
</pre>
My hack does only provide a valid path to an index.d.ts and ( @pcaridade-icg ) it works for ng build --prod, too.

**Comment by pcaridade-icg** [comment]
@FrankL-git I've checked my code again, despite the fact of having my package.json with version 1.1.4,  deleting the folder "node_modules" and performing a fresh install of all modules the actual version installed was 1.1.5 !?
Performing a npm uninstall and forcing a npm install @1.1.4 the code actually works with Angular 10 including ng build --prod . You were right, thank you. The problem still exists on 1.1.15, hope someone validate your suggestion or find another/better solution/explanation.

**Comment by Tush2890** [comment]
I was facing the same issue with my angular version 9.1.3 and angular-google-charts@1.1.5
After downgrading the google-charts version to 1.1.4, my ng build compiled successfully. Thank you for the all the discussions. It saved lot of my time.

**Comment by FERNman** [comment]
This should be fixed in the latest version! 🎉
